const stack = {
  ROOT: 'Splash',
  DASHBOARD: 'Dashboard',
  NAV_DRAWER: 'NavDrawer',
  LOGIN: 'Login',
  REGISTER: 'Register',
  LOGIN_SUCCESS: 'LoginSuccess',
  SUBSCRIPTION_LIST: 'SubscriptionList',
  SUBSCRIPTION_DETAILS: 'SubscriptionDetails',
  WEB_VIEW: 'WebViewScreen',
  CONTACT: 'Contactus',
  PROFILE: 'Profile',
  HOME: 'Home',
  NOTIFICATION: 'Notification',
  PAYMENTS: 'Payments',
  PROJECTS: 'Projects',
  REPORTS: 'Reports',
  ADD_ORGANIZATION: 'AddOrgDetails',
  EDIT_PROFILE: 'EditProfile',
  EDIT_PROFILE_USER: 'EditProfileUser',
  ADD_PROJECT: 'AddProject',
  ADD_TEAM: 'AddTeam',
  ADMIN_USER: 'AdminUsers',
  COMPANIES: 'Companies',
  WAREHOUSE: 'Warehouses',
  DRIVER_LIST: 'DriversList',
  MATERIAL_CATEGORY: 'MaterialCategories',
  MATERIAL_NAME: 'MaterialName',
  ADD_WAREHOUSE: 'AddWarehouse',
  ADD_MATERIAL_CAT: 'AddMaterialCat',
  ADD_MATERIAL_NAME: 'AddMaterialName',
  ADD_ADMIN_USER: 'AddAdminUsers',
  ADD_COMPANY: 'AddCompany',
  ADD_DRIVER: 'AddDriver',
  MEMBER_USER: 'MemberUsers',
  REGISTRATION_FEE: 'RegistrationFees',
  ORGANIZATION_DUES: 'OrganizationDues',
  ADD_MEMBER_USER: 'AddMemberUser',
  MY_SUBSCRIPTION_SCREEN: 'MySubscriptionScreen',
  VIEW_MORE_DUES: 'ViewMoreDues',
  ORG_SETTINGS: 'OrganizationSettings',
  PAYMENT_METHOD: 'PaymentMethod',
  RECEIVE_PAYMENT: 'ReceiveManualPayment',
  MESSAGE_WINDOW: 'MessageWindow',
  CMS_PAGE: 'CMSPage',
  MANAGE_MEETING: 'ManageMeeting',
  LABOUR_LIST: 'LabourList',
  PROJECT_LIST: 'ProjectList',
  ADD_LABOUR: 'AddLabour',
  ADD_MATERIAL_FROM_WAREHOUSE: 'AddMaterialsfromwarehouse',
  lbl_Category_hint: 'Category',
  lbl_Material_Name_hint: 'Material Name',
  MATERIAL_WAREHOUSE: 'MaterialFromWarehouses',

  MATERIAL_TRANSFER: 'MaterialTransfer',
  ADD_MATERIAL_TRANSFER: 'AddMaterialTransfer',
  SETTINGS: 'Settings',
  MATERIAL_SUB_LIST: 'MaterialSubList',

  PROJECT_FUND: 'ProjectFundList',
  ADD_PROJECT_FUND: 'AddProjectFund',
  ADD_PROJECT_FUND_KISHAN: 'AddProjectFundKishanBhai',
  ADD_PROJECT_FUND_DINESH: 'AddProjectFundDineshBhai',
  ADD_PROJECT_FUND_ACCOUNT: 'AddProjectFundAccountPerson',
  ADD_PROJECT_SUPER_ADMIN: 'AddProjectFundSuperAdmin',

  ADD_EXPENSE_CATEGORY: 'AddExpenseCategory',
  EXPENSE_CATEGORY: 'ExpenseCategory',

  ADD_EXPENSE: 'AddExpense',
  EXPENSE_LIST: 'ExpenseList',
};

const deviceInfo = {
  // If you change and value name here then you should have to change name in Native module. :"DeviceInfoModule"
  VERSION: 'AppVersion',
  MODEL: 'ModelName',
  BRAND: 'BrandName',
  PACKAGE: 'PackageName',
  CODE: 'AppCode',
};

const appMessagesKey = {
  START_YOUR_JOURNEY_WITH_US: 'START_YOUR_JOURNEY_WITH_US',
};
const dateFormat = {
  POSTING: 'yyyy-MM-DD',
  DISPLAY: 'DD/MM/YYYY',
  DISPLAY_MONTH: 'MMMM',
  DISPLAY_MONTH_SHORT: 'MMM',
};
export {stack, deviceInfo, appMessagesKey, dateFormat};
