import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    lbl_Login: 'Login',
    lbl_mobile_hint: 'Mobile Number',
    lbl_password_hint: 'Password',
    btn_login: 'Log in',
    lbl_forgot_password: 'Forgot password?',
    msg_enter_mobile: 'Please enter Mobile number',
    msg_valid_mobile: 'Please enter valid Mobile number',
    msg_enter_pass: 'Please enter password',
    msg_valid_pass: 'Please enter valid password',
    lbl_menu_user: 'Users',
    lbl_menu_company: 'Company',
    lbl_menu_warehouse: 'Warehouse',
    lbl_menu_materialCat: 'Material Category',
    lbl_menu_materialName: 'Material',
    lbl_menu_driver: 'Driver',
    lbl_menu_labour: 'Labour',
    lbl_active_status: 'Active',
    lbl_inactive_status: 'In active',
    lbl_no_records: 'No records found',
    lbl_add_user: 'Add User',
    lbl_edit_user: 'Edit User',
    lbl_name_hint: 'Name',
    lbl_licence_hint: 'Licence',
    lbl_aadhar_no_hint: 'Aadhar Number',
    lbl_company_name_hint: 'Company name',
    lbl_email_hint: 'Email',
    lbl_status_hint: 'Status',
    lbl_role_hint: 'Role',
    btn_save: 'Save',
    btn_update: 'Update',
    btn_delete: 'Delete',
    msg_name: 'Please enter name',
    msg_company_name: 'Please enter company name',
    msg_warehouse_name: 'Please enter warehouse name',
    msg_driver_name: 'Please enter driver name',
    msg_labour_name: 'Please enter labour name',
    msg_aadhar_no: 'Please enter aadhar number',
    msg_no_person: 'Please enter number of person',
    msg_licence_name: 'Please enter licence number',
    msg_nameSize_name: 'Please enter name size',
    msg_materialcat_name: 'Please enter material category name',
    msg_gst: 'Please enter gst',
    msg_enter_email: 'Please enter email address',
    msg_valid_email: 'Please enter valid email address',
    msg_enter_status: 'Please select status	',

    msg_enter_city: 'Please select city',
    msg_enter_state: 'Please select state',
    msg_enter_category: 'Please select category',
    msg_enter_company: 'Please select company',
    lbl_select_status: 'Select status',
    lbl_select_company: 'Select company',
    btn_close: 'Close',
    msg_something_wrong: 'Something went wrong.',
    btn_yes_delete: 'Yes, Delete',
    btn_yes: 'Yes',
    btn_cancel: 'Cancel',
    msg_delete: 'Are you sure you want to delete?',
    msg_change_status: 'Are you sure you want to change status?',
    lbl_gst_hint: 'GST',
    lbl_add_company: 'Add Company',
    lbl_add_driver: 'Add Driver',
    lbl_edit_driver: 'Edit Driver',
    lbl_add_labour: 'Add Labour',
    lbl_edit_labour: 'Edit Labour',
    lbl_edit_company: 'Edit Company',
    lbl_add_warehouse: 'Add Warehouse',
    lbl_edit_warehouse: 'Edit Warehouse',
    lbl_warehouse_name_hint: 'Warehouse name',
    lbl_name_size_hint: 'Material Name',
    lbl_select_city: 'Select City',
    lbl_select_state: 'Select State',
    lbl_select_category: 'Select Category',
    lbl_city_hint: 'City',
    lbl_state_hint: 'State',
    lbl_category_hint: 'Category',
    lbl_material_category: 'Material Category name',
    lbl_add_materialCat: 'Add Material Category',
    lbl_edit_materialCat: 'Edit Material Category',
    lbl_add_materialName: 'Add Material Name',
    lbl_edit_materialName: 'Edit Material Name',
    lbl_choose_media: 'Choose Media',
    btn_camera: 'Camera',
    btn_gallery: 'Gallery',
    lbl_no_of_person: 'No. of Person',
    lbl_menu_logout: 'Logout',
    lbl_menu_project: 'Project',
    lbl_menu_MaterialList_From_WareHouse: 'Material Entries',
    msg_select_company_name: 'Please select at least company',
    msg_select_role: 'Please select role',
    msg_workIn_Progress: 'Work In Progress',
    lbl_create_new_project: 'Create New Project',
    lbl_edit_project: 'Edit Project',
    lbl_project_name_hint: 'Project Name',
    lbl_address_hint: 'Address',
    lbl_remarks_hint: 'Remarks',
    lbl_start_date_hint: 'Start date',
    lbl_end_date_hint: 'End Date',
    msg_formGreaterThanTo:
      'Start date should be less than or equal to End date',
    msg_geaterThanCurrDate:
      'Start and End dates should not be less than current date',
    msg_select_start_date_first: 'Please select start date first.',
    msg_enter_project_name: 'Please enter Project Name',
    msg_enter_address: 'Please enter Address',
    msg_enter_remarks: 'Please enter Remarks',
    msg_select_end_date: 'Please select end date',
    btn_add_team: 'Add Team',
    lbl_site_incharge_hint: 'Site Incharge',
    lbl_manager_hint: 'Developer',
    lbl_Superwisors_hint: 'Superwisors',
    lbl_Engineers_hint: 'Engineers',
    lbl_driver_hint: 'Account Person',
    lbl_Labour_hint: 'Labours',
    msg_select_siteIncharge: 'Please select site Incharge',
    msg_select_manager: 'Please select Developer',
    msg_select_superwisors: 'Please select Superwisors',
    msg_select_engineers: 'Please select Engineers',
    msg_select_driverHelper: 'Please select Account Person',
    msg_select_labour: 'Please select labour',
    lbl_quentity_hint: 'Quantity',
    lbl_Warehouse_header: 'Select Warehouse',
    lbl_MaterialName_header: 'Select Material Name',
    msg_MaterialName_select: 'Please Select Material Name',
    msg_Warehouse_select: 'Please Select Warehouse',
    lbl_qty_select: 'Please enter Quantity',
    lbl_qty_valid_select: 'Please enter valid Quantity',
    lbl_select_location_header: 'Select Location',
    msg_location_select: 'Please Select Location',
    lbl_search_hint: 'Search here',
    lbl_menu_MaterialList_transfer: 'Material Transfer',
    lbl_select_location_from_header: 'Select Transfer From Location',
    msg_location_from_select: 'Please Select Transfer From Location',
    lbl_select_location_to_header: 'Select Transfer To Location',
    msg_location_to_select: 'Please Select Transfer To Location',
    msg_Warehouse_from_select: 'Please Select Warehouse From',
    msg_Warehouse_to_select: 'Please Select Warehouse To',
    btn_Add_project_material: 'Add Materials Entry',
    btn_Update_project_material: 'Edit Materials Entry',
    btn_Add_trnasfer_project_material: 'Add Transfer Material Request',
    lbl_option_Requested: 'Requested',
    lbl_option_Delivered: 'Delivered',
    lbl_date: 'Date',
    msg_select_date: 'Please Select date',
    Role_Master_Admin: 'Master Admin',
    Role_Warehouse_person: 'Warehouse person',
    Role_Site_Incharge: 'Site Incharge',
    Role_Account_Persion: 'Account Person',
    lbl_projectfund_header: 'Income',
    lbl_settings_header: 'Settings',
    lbl_language_English: 'English',
    lbl_language_Hindi: 'Hindi',
    lbl_language_Gujarati: 'Gujarati',
    lbl_language_header: 'Language',
    lbl_Select_language_header: 'Select Language',
    msg_Select_language: 'Please Select Language',
    lbl_option_warehouse: 'warehouse',
    lbl_option_project: 'project',
    lbl_view: 'View',
    lbl_change_Status: 'Change Status',
    btn_update_status: 'Update Status',
    lbl_option_approved: 'Approved',
    lbl_option_rejected: 'Rejected',
    lbl_option_Canceled: 'Cancelled',
    lbl_menu_Material_entry: 'Material Entry',
    lbl_Requests: 'Requests',
    lbl_not_more_then: 'Not more then ##',
    lbl_qty_not_available: 'Quantity not available',
    lbl_Other_remarks_hint: 'Approved / Rejected remarks',
    lbl_del_remarks_hint: 'Delivered remarks',
    lbl_cancelled_remarks_hint: 'Cancelled remarks',
    lbl_transfer_from_warehouse: 'Transfer from Warehouse',
    lbl_transfer_from_project: 'Transfer from Project',
    lbl_transfer_to_warehouse: 'Transfer to Warehouse',
    lbl_transfer_to_project: 'Transfer to Project',
    msg_Warehouse_project_select: 'Please Select ##',
    msg_Warehouse_project_from_select: 'Please Select ## From',
    msg_Warehouse_project_to_select: 'Please Select ## To',
    lbl_delivered_quentity_hint: 'Delivered Quantity',
    lbl_delivered_qty_select: 'Please enter Delivered Quantity',
    lbl_delivered_qty_valid_select: 'Please enter valid Delivered Quantity',
    lbl_add_project_fund: 'Add Income',
    lbl_edit_project_fund: 'Edit Income',
    lbl_credit_mode: 'Shreekar to Project',
    lbl_debit_mode: 'Project to Shreekar',

    msg_enter_mode: 'Please select mode	',
    lbl_select_mode: 'Select mode',
    lbl_mode_hint: 'Payment Mode',
    lbl_r_amount_hint: 'Requested Amount',
    lbl_f_amount_hint: 'Approved Amount',
    lbl_v_amount_hint: 'Validated Amount',
    msg_valid_request_amount: 'Please enter valid requested amount',
    msg_valid_final_amount: 'Please enter valid approved amount',
    msg_enter_from_company: 'Please select from company',
    lbl_from_company_hint: 'From (Company)',
    lbl_purpose_hint: 'Purpose',
    lbl_option_validated: 'Validated',
    lbl_project_hint: 'For Project',
    lbl_select_project: 'Select Project',
    msg_enter_project: 'Please select Project',
    msg_enter_purpose: 'Please enter Purpose',
    lbl_project_fund_entries: 'Income Entries',
    btn_request: 'Request',
    lbl_menu_expense_category: 'Expense Category',
    lbl_add_expense_category: 'Add Expense Category',
    lbl_edit_expense_category: 'Edit Expense Category',
    lbl_expense_category: 'Expense Category name',
    msg_expense_cat_name: 'Please enter expense category name',
    lbl_menu_Expense: 'Expense',
    lbl_add_expense: 'Add Expense',
    lbl_edit_expense: 'Edit Expense',
    lbl_amount_hint: 'Amount',
    lbl_voucher_hint: 'Voucher No.',
    msg_valid_amount: 'Please enter valid amount',
    lbl_select_expense_category: 'Select Expense Category',
  },
  hi: {
    lbl_option_warehouse: 'warehouse',
    lbl_option_project: 'project',
    lbl_Login: 'लॉगिन',
    lbl_mobile_hint: 'मोबाइल नंबर',
    lbl_password_hint: 'पासवर्ड',
    btn_login: 'लॉग इन करें',
    lbl_forgot_password: 'पासवर्ड भूल गए?',
    msg_enter_mobile: 'कृपया मोबाइल नंबर दर्ज करें',
    msg_valid_mobile: 'कृपया वैध मोबाइल नंबर दर्ज करें',
    msg_enter_pass: 'कृपया पासवर्ड दर्ज करें',
    msg_valid_pass: 'कृपया वैध पासवर्ड दर्ज करें',
    lbl_menu_user: 'उपयोगकर्ता',
    lbl_menu_company: 'कंपनी',
    lbl_menu_warehouse: 'गोदाम',
    lbl_menu_materialCat: 'सामग्री श्रेणी',
    lbl_menu_materialName: 'सामग्री',
    lbl_menu_driver: 'ड्राइवर',
    lbl_menu_labour: 'श्रमिक',
    lbl_active_status: 'सक्रिय',
    lbl_inactive_status: 'निष्क्रिय',
    lbl_no_records: 'कोई रिकॉर्ड नहीं मिला',
    lbl_add_user: 'उपयोगकर्ता जोड़ें',
    lbl_edit_user: 'उपयोगकर्ता संपादित करें',
    lbl_name_hint: 'नाम',
    lbl_licence_hint: 'लाइसेंस',
    lbl_aadhar_no_hint: 'आधार नंबर',
    lbl_company_name_hint: 'कंपनी का नाम',
    lbl_email_hint: 'ईमेल',
    lbl_status_hint: 'स्थिति',
    lbl_role_hint: 'भूमिका',
    btn_save: 'सहेजें',
    btn_update: 'अपडेट करें',
    btn_delete: 'हटाएं',
    msg_name: 'कृपया नाम दर्ज करें',
    msg_company_name: 'कृपया कंपनी का नाम दर्ज करें',
    msg_warehouse_name: 'कृपया वेयरहाउस नाम दर्ज करें',
    msg_driver_name: 'कृपया चालक का नाम दर्ज करें',
    msg_labour_name: 'कृपया श्रमिक का नाम दर्ज करें',
    msg_aadhar_no: 'कृपया आधार नंबर दर्ज करें',
    msg_no_person: 'कृपया व्यक्तियों की संख्या दर्ज करें',
    msg_licence_name: 'कृपया लाइसेंस नंबर दर्ज करें',
    msg_nameSize_name: 'कृपया नाम का आकार दर्ज करें',
    msg_materialcat_name: 'कृपया सामग्री श्रेणी का नाम दर्ज करें',
    msg_gst: 'कृपया जीएसटी दर्ज करें',
    msg_enter_email: 'कृपया ईमेल पता दर्ज करें',
    msg_valid_email: 'कृपया मान्य ईमेल पता दर्ज करें',
    msg_enter_status: 'कृपया स्थिति का चयन करें',
    msg_enter_city: 'कृपया शहर का चयन करें',
    msg_enter_state: 'कृपया राज्य का चयन करें',
    msg_enter_category: 'कृपया श्रेणी का चयन करें',
    msg_enter_company: 'कृपया कंपनी का चयन करें',
    lbl_select_status: 'स्थिति चयन करें',
    lbl_select_company: 'कंपनी चयन करें',
    btn_close: 'बंद करें',
    msg_something_wrong: 'कुछ गलत हो गया है।',
    btn_yes_delete: 'हां, हटाएं',
    btn_yes: 'हां',
    btn_cancel: 'रद्द करें',
    msg_delete: 'क्या आप सुनिश्चित हैं कि आप हटाना चाहते हैं?',
    msg_change_status: 'क्या आप वाकई स्थिति बदलना चाहते हैं?',
    lbl_gst_hint: 'जीएसटी',
    lbl_add_company: 'कंपनी जोड़ें',
    lbl_add_driver: 'चालक जोड़ें',
    lbl_edit_driver: 'चालक संपादित करें',
    lbl_add_labour: 'श्रमिक जोड़ें',
    lbl_edit_labour: 'श्रमिक संपादित करें',
    lbl_edit_company: 'कंपनी संपादित करें',
    lbl_add_warehouse: 'वेयरहाउस जोड़ें',
    lbl_edit_warehouse: 'वेयरहाउस संपादित करें',
    lbl_warehouse_name_hint: 'वेयरहाउस का नाम',
    lbl_name_size_hint: 'सामग्री का नाम',
    lbl_select_city: 'शहर चयन करें',
    lbl_select_state: 'राज्य चयन करें',
    lbl_select_category: 'श्रेणी चयन करें',
    lbl_city_hint: 'शहर',
    lbl_state_hint: 'राज्य',
    lbl_category_hint: 'श्रेणी',
    lbl_material_category: 'सामग्री श्रेणी नाम',
    lbl_add_materialCat: 'सामग्री श्रेणी जोड़ें',
    lbl_edit_materialCat: 'सामग्री श्रेणी संपादित करें',
    lbl_add_materialName: 'सामग्री का नाम जोड़ें',
    lbl_edit_materialName: 'सामग्री का नाम संपादित करें',
    lbl_choose_media: 'मीडिया चयन करें',
    btn_camera: 'कैमरा',
    btn_gallery: 'गैलरी',
    lbl_no_of_person: 'व्यक्तियों की संख्या',
    lbl_menu_logout: 'लॉगआउट',
    lbl_menu_project: 'परियोजना',
    lbl_menu_MaterialList_From_WareHouse: 'सामग्री इन्ट्रीज',
    msg_select_company_name: 'कृपया कम से कम कंपनी का चयन करें',
    msg_select_role: 'कृपया भूमिका का चयन करें',
    msg_workIn_Progress: 'काम जारी है',
    lbl_create_new_project: 'नई परियोजना बनाएं',
    lbl_edit_project: 'परियोजना संपादित करें',
    lbl_project_name_hint: 'परियोजना का नाम',
    lbl_address_hint: 'पता',
    lbl_remarks_hint: 'टिप्पणियाँ',
    lbl_start_date_hint: 'प्रारंभ तिथि',
    lbl_end_date_hint: 'समाप्ति तिथि',
    msg_formGreaterThanTo:
      'प्रारंभ तिथि समाप्ति तिथि से कम होनी चाहिए या इसके बराबर होनी चाहिए',
    msg_geaterThanCurrDate:
      'प्रारंभ और समाप्ति तिथियां वर्तमान तिथि से कम नहीं होनी चाहिए',
    msg_select_start_date_first: 'कृपया पहले प्रारंभ तिथि का चयन करें।',
    msg_enter_project_name: 'कृपया परियोजना का नाम दर्ज करें',
    msg_enter_address: 'कृपया पता दर्ज करें',
    msg_enter_remarks: 'कृपया टिप्पणियाँ दर्ज करें',
    msg_select_end_date: 'कृपया समाप्ति तिथि का चयन करें',
    btn_add_team: 'टीम जोड़ें',
    lbl_site_incharge_hint: 'साइट इंचार्ज',
    lbl_manager_hint: 'डेवेलपर',
    lbl_Superwisors_hint: 'सुपरवाइज़र्स',
    lbl_Engineers_hint: 'इंजीनियर्स',
    lbl_driver_hint: 'अकाउंट पर्सन',
    lbl_Labour_hint: 'श्रमिक',
    msg_select_siteIncharge: 'कृपया साइट इंचार्ज का चयन करें',
    msg_select_manager: 'कृपया डेवेलपर का चयन करें',
    msg_select_superwisors: 'कृपया सुपरवाइज़र्स का चयन करें',
    msg_select_engineers: 'कृपया इंजीनियर्स का चयन करें',
    msg_select_driverHelper: 'कृपया अकाउंट पर्सन का चयन करें',
    msg_select_labour: 'कृपया श्रमिक का चयन करें',
    lbl_quentity_hint: 'मात्रा',
    lbl_Warehouse_header: 'वेयरहाउस चुनें',
    lbl_MaterialName_header: 'सामग्री का नाम चुनें',
    msg_MaterialName_select: 'कृपया सामग्री का नाम चुनें',
    msg_Warehouse_select: 'कृपया वेयरहाउस का चयन करें',
    lbl_qty_select: 'कृपया मात्रा दर्ज करें',
    lbl_qty_valid_select: 'कृपया वैध मात्रा दर्ज करें',
    lbl_select_location_header: 'स्थान चुनें',
    msg_location_select: 'कृपया स्थान चुनें',
    lbl_search_hint: 'यहाँ खोजें',
    lbl_menu_MaterialList_transfer: 'सामग्री स्थानांतरण',
    lbl_select_location_from_header: 'स्थान से स्थानांतरण का चयन करें',
    msg_location_from_select: 'कृपया स्थान से स्थानांतरण का चयन करें',
    lbl_select_location_to_header: 'स्थानांतरण के लिए स्थान का चयन करें',
    msg_location_to_select: 'कृपया स्थानांतरण के लिए स्थान का चयन करें',
    msg_Warehouse_from_select: 'कृपया से वेयरहाउस का चयन करें',
    msg_Warehouse_to_select: 'कृपया को वेयरहाउस का चयन करें',
    btn_Add_project_material: 'सामग्री एंट्री जोड़ें',
    btn_Update_project_material: 'सामग्री एंट्री संपादित करें',
    btn_Add_trnasfer_project_material: 'स्थानांतरण सामग्री अनुरोध जोड़ें',
    lbl_option_Requested: 'Requested',
    lbl_option_Delivered: 'Delivered',
    lbl_date: 'तारीख',
    msg_select_date: 'कृपया तारीख का चयन करें',
    Role_Master_Admin: 'मास्टर एडमिन',
    Role_Warehouse_person: 'वेयरहाउस व्यक्ति',
    Role_Site_Incharge: 'साइट इंचार्ज',
    Role_Account_Persion: 'Account Person',
    lbl_settings_header: 'सेटिंग्स',
    lbl_projectfund_header: 'परियोजना निधि',
    lbl_language_English: 'अंग्रेजी',
    lbl_language_Hindi: 'हिंदी',
    lbl_language_Gujarati: 'गुजराती',
    lbl_language_header: 'भाषा',
    lbl_Select_language_header: 'भाषा का चयन करें',
    msg_Select_language: 'कृपया भाषा चुनें',
    lbl_option_warehouse: 'गोदाम',
    lbl_option_project: 'परियोजना',
    lbl_view: 'देखें',
    lbl_change_Status: 'स्थिति बदलें',
    btn_update_status: 'स्थिति अपडेट करें',
    lbl_option_approved: 'Approved',
    lbl_option_rejected: 'Rejected',
    lbl_option_Canceled: 'Cancelled',
    lbl_menu_Material_entry: 'सामग्री प्रविष्टि',
    lbl_Requests: 'अनुरोध',
    lbl_not_more_then: '## से अधिक नहीं',
    lbl_qty_not_available: 'मात्रा उपलब्ध नहीं है',
    lbl_Other_remarks_hint: 'स्वीकृत/अस्वीकृत टिप्पणियाँ',
    lbl_del_remarks_hint: 'टिप्पणियाँ दीं',
    lbl_cancelled_remarks_hint: 'रद्द की गई टिप्पणियाँ',
    lbl_transfer_from_warehouse: 'गोदाम से स्थानांतरण',
    lbl_transfer_from_project: 'परियोजना से स्थानांतरण',
    lbl_transfer_to_warehouse: 'गोदाम में स्थानांतरण',
    lbl_transfer_to_project: 'परियोजना में स्थानांतरण',
    msg_Warehouse_project_select: 'कृपया ## का चयन करें',
    msg_Warehouse_project_from_select: 'कृपया ## का चयन करें',
    msg_Warehouse_project_to_select: 'कृपया ## को चुनें',
    lbl_delivered_quentity_hint: 'वितरित मात्रा',
    lbl_delivered_qty_select: 'कृपया वितरित मात्रा दर्ज करें',
    lbl_delivered_qty_valid_select: 'कृपया मान्य वितरित मात्रा दर्ज करें',
    lbl_add_project_fund: 'प्रोजेक्ट फंड जोड़ें',
    lbl_edit_project_fund: 'परियोजना निधि संपादित करें',
    lbl_credit_mode: 'श्रेय',
    lbl_debit_mode: 'नामे',
  },
  gu: {
    lbl_option_warehouse: 'warehouse',
    lbl_option_project: 'project',
    lbl_Login: 'લોગિન',
    lbl_mobile_hint: 'મોબાઇલ નંબર',
    lbl_password_hint: 'પાસવર્ડ',
    btn_login: 'લોગ ઇન કરો',
    lbl_forgot_password: 'પાસવર્ડ ભૂલાઈ?',
    msg_enter_mobile: 'કૃપા કરીને મોબાઇલ નંબર દાખલ કરો',
    msg_valid_mobile: 'કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો',
    msg_enter_pass: 'કૃપા કરીને પાસવર્ડ દાખલ કરો',
    msg_valid_pass: 'કૃપા કરીને માન્ય પાસવર્ડ દાખલ કરો',
    lbl_menu_user: 'વપરાશકર્તાઓ',
    lbl_menu_company: 'કંપની',
    lbl_menu_warehouse: 'વેરહાઉસ',
    lbl_menu_materialCat: 'સામગ્રી શ્રેણી',
    lbl_menu_materialName: 'સામગ્રી',
    lbl_menu_driver: 'ડ્રાઈવર',
    lbl_menu_labour: 'શ્રમિક',
    lbl_active_status: 'સક્રિય',
    lbl_inactive_status: 'નકારાત્મક',
    lbl_no_records: 'કોઈ રેકોર્ડ મળ્યો નથી',
    lbl_add_user: 'વપરાશકર્તા ઉમેરો',
    lbl_edit_user: 'વપરાશકર્તા સંપાદિત કરો',
    lbl_name_hint: 'નામ',
    lbl_licence_hint: 'લાઇસન્સ',
    lbl_aadhar_no_hint: 'આધાર નંબર',
    lbl_company_name_hint: 'કંપની નામ',
    lbl_email_hint: 'ઇમેઇલ',
    lbl_status_hint: 'સ્થિતિ',
    lbl_role_hint: 'ભૂમિકા',
    btn_save: 'સાચવો',
    btn_update: 'અપડેટ કરો',
    btn_delete: 'કાઢવો',
    msg_name: 'કૃપા કરીને નામ દાખલ કરો',
    msg_company_name: 'કૃપા કરીને કંપની નામ દાખલ કરો',
    msg_warehouse_name: 'કૃપા કરીને વેઅહાઉસ નામ દાખલ કરો',
    msg_driver_name: 'કૃપા કરીને ચાલક નામ દાખલ કરો',
    msg_labour_name: 'કૃપા કરીને શ્રમિક નામ દાખલ કરો',
    msg_aadhar_no: 'કૃપા કરીને આધાર નંબર દાખલ કરો',
    msg_no_person: 'કૃપા કરીને વ્યક્તિઓની સંખ્યા દાખલ કરો',
    msg_licence_name: 'કૃપા કરીને લાઇસન્સ નંબર દાખલ કરો',
    msg_nameSize_name: 'કૃપા કરીને નામ મોટાઈ દાખલ કરો',
    msg_materialcat_name: 'કૃપા કરીને સામગ્રી શ્રેણી નામ દાખલ કરો',
    msg_gst: 'કૃપા કરીને GST દાખલ કરો',
    msg_enter_email: 'કૃપા કરીને ઇમેઇલ સરનામું દાખલ કરો',
    msg_valid_email: 'કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો',
    msg_enter_status: 'કૃપા કરીને સ્થિતિ પસંદ કરો',
    msg_enter_city: 'કૃપા કરીને શહેર પસંદ કરો',
    msg_enter_state: 'કૃપા કરીને રાજ્ય પસંદ કરો',
    msg_enter_category: 'કૃપા કરીને શ્રેણી પસંદ કરો',
    msg_enter_company: 'કૃપા કરીને કંપની પસંદ કરો',
    lbl_select_status: 'સ્થિતિ પસંદ કરો',
    lbl_select_company: 'કંપની પસંદ કરો',
    btn_close: 'બંધ કરો',
    msg_something_wrong: 'કંઈ ખોટું થયું છે.',
    btn_yes_delete: 'હા, કાઢો',
    btn_yes: 'હા',
    btn_cancel: 'રદ કરો',
    msg_delete: 'શું તમે ખાતરી છો કે તમારો મુકાબલો કરવો છો?',
    msg_change_status: 'શું તમે ખરેખર સ્થિતિ બદલવા માંગો છો?',
    lbl_gst_hint: 'GST',
    lbl_add_company: 'કંપની ઉમેરો',
    lbl_add_driver: 'ચાલક ઉમેરો',
    lbl_edit_driver: 'ચાલક સુધારો',
    lbl_add_labour: 'શ્રમિક ઉમેરો',
    lbl_edit_labour: 'શ્રમિક સુધારો',
    lbl_edit_company: 'કંપની સુધારો',
    lbl_add_warehouse: 'વેઅહાઉસ ઉમેરો',
    lbl_edit_warehouse: 'વેઅહાઉસ સુધારો',
    lbl_warehouse_name_hint: 'વેઅહાઉસ નામ',
    lbl_name_size_hint: 'સામગ્રી નામ',
    lbl_select_city: 'શહેર પસંદ કરો',
    lbl_select_state: 'રાજ્ય પસંદ કરો',
    lbl_select_category: 'શ્રેણી પસંદ કરો',
    lbl_city_hint: 'શહેર',
    lbl_state_hint: 'રાજ્ય',
    lbl_category_hint: 'શ્રેણી',
    lbl_material_category: 'સામગ્રી શ્રેણી નામ',
    lbl_add_materialCat: 'સામગ્રી શ્રેણી ઉમેરો',
    lbl_edit_materialCat: 'સામગ્રી શ્રેણી સુધારો',
    lbl_add_materialName: 'સામગ્રી નામ ઉમેરો',
    lbl_edit_materialName: 'સામગ્રી નામ સુધારો',
    lbl_choose_media: 'મીડિયા પસંદ કરો',
    btn_camera: 'કેમેરા',
    btn_gallery: 'ગેલેરી',
    lbl_no_of_person: 'વ્યક્તિઓની સંખ્યા',
    lbl_menu_logout: 'લૉગઆઉટ',
    lbl_menu_project: 'પરિયોજના',
    lbl_menu_MaterialList_From_WareHouse: 'સામગ્રી એન્ટ્રીઝ',
    msg_select_company_name: 'કૃપા કરીને ઓળખ કંપની પસંદ કરો',
    msg_select_role: 'કૃપા કરીને ભૂમિકા પસંદ કરો',
    msg_workIn_Progress: 'ચાલુ રહ્યું છે',
    lbl_create_new_project: 'નવું પરિયોજના બનાવો',
    lbl_edit_project: 'પરિયોજના સુધારો',
    lbl_project_name_hint: 'પરિયોજના નામ',
    lbl_address_hint: 'સરનામું',
    lbl_remarks_hint: 'ટિપ્પણિઓ',
    lbl_start_date_hint: 'પ્રારંભ તારીખ',
    lbl_end_date_hint: 'અંતિમ તારીખ',
    msg_formGreaterThanTo:
      'પ્રારંભ તારીખ ચાલુ તારીખથી ઓછી અથવા તેમના સમાન હોવી ચાહિએ',
    msg_geaterThanCurrDate:
      'પ્રારંભ અને અંતિમ તારીખો વર્તમાન તારીખ કરતાં ઓછી નહીં હોવી ચાહિએ',
    msg_select_start_date_first: 'કૃપા કરીને પ્રથમ પ્રારંભ તારીખ પસંદ કરો.',
    msg_enter_project_name: 'કૃપા કરીને પરિયોજના નામ દાખલ કરો',
    msg_enter_address: 'કૃપા કરીને સરનામું દાખલ કરો',
    msg_enter_remarks: 'કૃપા કરીને ટિપ્પણિઓ દાખલ કરો',
    msg_select_end_date: 'કૃપા કરીને અંતિમ તારીખ પસંદ કરો',
    btn_add_team: 'ટીમ ઉમેરો',
    lbl_site_incharge_hint: 'સાઇટ ઇનચાર્જ',
    lbl_manager_hint: 'ડેવલપર',
    lbl_Superwisors_hint: 'સુપરવાઇઝર્સ',
    lbl_Engineers_hint: 'ઇન્જિનિયર્સ',
    lbl_driver_hint: 'એકાઉન્ટ પર્સન',
    lbl_Labour_hint: 'શ્રમિકો',
    msg_select_siteIncharge: 'કૃપા કરીને સાઇટ ઇનચાર્જ પસંદ કરો',
    msg_select_manager: 'કૃપા કરીને ડેવલપર પસંદ કરો',
    msg_select_superwisors: 'કૃપા કરીને સુપરવાઇઝર્સ પસંદ કરો',
    msg_select_engineers: 'કૃપા કરીને ઇન્જનિયર્સ પસંદ કરો',
    msg_select_driverHelper: 'કૃપા કરીને એકાઉન્ટ પર્સન પસંદ કરો',
    msg_select_labour: 'કૃપા કરીને શ્રમિક પસંદ કરો',
    lbl_quentity_hint: 'પ્રમાણ',
    lbl_Warehouse_header: 'વેરહાઉસ પસંદ કરો',
    lbl_MaterialName_header: 'સામગ્રીનું નામ પસંદ કરો',
    msg_MaterialName_select: 'કૃપા કરીને સામગ્રીનું નામ પસંદ કરો',
    msg_Warehouse_select: 'કૃપા કરીને વેરહાઉસ પસંદ કરો',
    lbl_qty_select: 'કૃપા કરીને જથ્થો દાખલ કરો',
    lbl_qty_valid_select: 'કૃપા કરીને માન્ય જથ્થો દાખલ કરો',
    lbl_select_location_header: 'સ્થાન પસંદ કરો',
    msg_location_select: 'કૃપા કરીને સ્થાન પસંદ કરો',
    lbl_search_hint: 'અહીં શોધો',
    lbl_menu_MaterialList_transfer: 'સામગ્રી ટ્રાન્સફર',
    lbl_select_location_from_header: 'સ્થાનાંતરણ થવાના સ્થાન પસંદ કરો',
    msg_location_from_select: 'કૃપા કરીને સ્થાનાંતરણ થવાના સ્થાન પસંદ કરો',
    lbl_select_location_to_header: 'સ્થાનાંતરણ માટે સ્થાન પસંદ કરો',
    msg_location_to_select: 'કૃપા કરીને સ્થાનાંતરણ માટે સ્થાન પસંદ કરો',
    msg_Warehouse_from_select: 'કૃપા કરીને વેરહાઉસ થવાના પસંદ કરો',
    msg_Warehouse_to_select: 'કૃપા કરીને વેરહાઉસ માટે પસંદ કરો',
    btn_Add_project_material: 'સામગ્રી એન્ટ્રી ઉમેરો',
    btn_Update_project_material: 'સામગ્રી એન્ટ્રી સંપાદિત કરો',
    btn_Add_trnasfer_project_material: 'સામગ્રી ટ્રાન્સફર વિનંતી ઉમેરો',
    lbl_option_Requested: 'Requested',
    lbl_option_Delivered: 'Delivered',
    lbl_date: 'તારીખ',
    msg_select_date: 'કૃપા કરીને તારીખ પસંદ કરો',
    Role_Master_Admin: 'માસ્ટર એડમિન',
    Role_Warehouse_person: 'વેરહાઉસ પર્સન',
    Role_Site_Incharge: 'સાઇટ ઇનચાર્જ',
    Role_Account_Persion: 'Account Person',
    lbl_settings_header: 'સેટિંગ્સ',
    lbl_projectfund_header: 'પ્રોજેક્ટ ફંડ',
    lbl_language_English: 'ઇંગ્લિશ',
    lbl_language_Hindi: 'હિન્દી',
    lbl_language_Gujarati: 'ગુજરાતી',
    lbl_language_header: 'ભાષા',
    lbl_Select_language_header: 'ભાષા પસંદ કરો',
    msg_Select_language: 'કૃપા કરીને ભાષા પસંદ કરો',
    lbl_option_warehouse: 'વેરહાઉસ',
    lbl_option_project: 'પ્રોજેક્ટ',
    lbl_view: 'જુઓ',
    lbl_change_Status: 'સ્થિતિ બદલો',
    btn_update_status: 'સ્થિતિ અપડેટ કરો',
    lbl_option_approved: 'Approved',
    lbl_option_rejected: 'Rejected',
    lbl_option_Canceled: 'Cancelled',
    lbl_menu_Material_entry: 'સામગ્રી એન્ટ્રી',
    lbl_Requests: 'વિનંતિઓ',
    lbl_not_more_then: '## થી વધુ નહીં',
    lbl_qty_not_available: 'જથ્થો ઉપલબ્ધ નથી',
    lbl_Other_remarks_hint: 'મંજૂર / અસ્વીકારિત ટિપ્પણી',
    lbl_del_remarks_hint: 'વિતરિત ટિપ્પણીઓ',
    lbl_cancelled_remarks_hint: 'રદ કરેલી ટિપ્પણી',
    lbl_transfer_from_warehouse: 'વેરહાઉસમાંથી ટ્રાન્સફર',
    lbl_transfer_from_project: 'પ્રોજેક્ટમાંથી ટ્રાન્સફર',

    lbl_transfer_to_warehouse: 'વેરહાઉસમાં સ્થાનાંતરિત કરો',
    lbl_transfer_to_project: 'પ્રોજેક્ટમાં ટ્રાન્સફર કરો',
    msg_Warehouse_project_select: 'કૃપા કરીને ## પસંદ કરો',

    msg_Warehouse_project_from_select: 'કૃપા કરીને આમાંથી ## પસંદ કરો',
    msg_Warehouse_project_to_select: 'કૃપા કરીને ## માટે પસંદ કરો',
    lbl_delivered_quentity_hint: 'વિતરિત જથ્થો',
    lbl_delivered_qty_select: 'કૃપા કરીને વિતરિત જથ્થો દાખલ કરો',
    lbl_delivered_qty_valid_select: 'કૃપા કરીને માન્ય વિતરિત જથ્થો દાખલ કરો',
    lbl_add_project_fund: 'પ્રોજેક્ટ ફંડ ઉમેરો',
    lbl_edit_project_fund: 'પ્રોજેક્ટ ફંડમાં ફેરફાર કરો',
    lbl_credit_mode: 'જમા',
    lbl_debit_mode: 'ઉધાર',
  },
});
export default strings;
